[project]
name = "2024"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = "==3.13.0"
dependencies = [
  "kagglehub==0.3.4",
  "openai==1.55.0",
  "tiktoken==0.8.0",
  "tqdm==4.67.0",
]
